# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e282f97bc299480163a7254d0061becbc9e898428e0d37b2d1ca8aec49a4d4fbd60e64bf2158f661d46758cf3fef94c860e3a34b95be34f47bb4f00cdc75ee9e

test:
  secret_key_base: 0dedffc30c8b48c9481ee5a662cfb9fc01aac389bb8255f89b30273d83af5b93db2d289c993ac398399d1bf78cff7a1aef835ca995c3919de2e67f2cb5e7284c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
